### ISSUE TITLE
Macro ticket: create a new scaler for SWIFT.

### ISSUE THREAD

**Issue by robsondepaula** [sidilabs/keda#14]
A clear and concise description of what scaler you'd like to use and how you'd want to use it:

  - **Scaler Source:** https://www.openstack.org/software/releases/victoria/components/swift
  - **How do you want to scale:** *Please elaborate*
  - **Authentication:** *Please elaborate*

**Comment by domminiks** [comment]
Steps to build a KEDA scaler:

1. Download KEDA files.
2. Define which parameters the Trigger should get from the user.
3. Implement the Scaler [interface](https://github.com/sidilabs/keda/blob/autosync/pkg/scalers/scaler.go):
    1. `NewScalerName()`: the constructor;
    2. `GetMetrics()`: the scaler returns the metric values for a metric name and criteria matching the selector. It returns the value for a supported metric and an error if there is a problem getting the metric. It connects to OpenStack Swift and finds the number of elements inside a container; 
    3. `GetMetricSpecForScaling()`: returns the metric spec for the HPA;
    4. `IsActive()`: if we have to scale from zero. It checks if there is an element in the Swift container, for example;
    5. `Close()`: close any resources that need disposing when scaler is no longer used or destroyed;
    6. `parseScalerMetadata()`;
4. Add entry in switch-case [scale_handler.go](https://github.com/sidilabs/keda/blob/autosync/pkg/scaling/scale_handler.go).
5. Test it (`make build/publish/deploy`).

**Comment by domminiks** [comment]
For OpenStack authentication we use Keystone. With Keystone, one can get an access token to be used for authentication/authorization. Currently, we are investigating two auth methods for querying the Swift API:

- Username/Password (it works if we provide admin user credentials. Need to investigate with different users)
- [Application Credentials](https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=#application-credentials) (need to investigate the correct roles and access rules to be set or if maybe it is a Swift configuration problem)

**Comment by domminiks** [comment]
A trigger specification for Swift could look like:

```yaml
triggers:
- type: openstack-swift
  metadata:
		swiftURL: http://<openstack_host>:<swift_port>/v1/AUTH_<project_ID>
    containerName: my-container # Required: Name of OpenStack Swift container
    objectCount: '5' # Optional. Amount of objects to scale out on. Default: 5 objects
		authenticationRef:
        name: openstack-swift-auth
```
